name: Bot Shopee Telegram

on:
  schedule:
    - cron: '0 12 * * *'   # 09:00 Brasília
    - cron: '0 13 * * *'   # 10:00 Brasília
    - cron: '0 14 * * *'   # 11:00 Brasília
    - cron: '0 15 * * *'   # 12:00 Brasília
    - cron: '0 16 * * *'   # 13:00 Brasília
    - cron: '41 17 * * *'  # 14:41 Brasília
    - cron: '0 18 * * *'   # 15:00 Brasília
    - cron: '57 19 * * *'  # 16:57 Brasília
    - cron: '13 20 * * *'  # 17:13 Brasília
    - cron: '0 21 * * *'   # 18:00 Brasília
    - cron: '0 22 * * *'   # 19:00 Brasília
    - cron: '0 23 * * *'   # 20:00 Brasília
    - cron: '0 0 * * *'    # 21:00 Brasília (meia-noite UTC)
    - cron: '0 1 * * *'    # 22:00 Brasília
    - cron: '0 2 * * *'    # 23:00 Brasília
    - cron: '59 4 * * *'   # 01:59 Brasília
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Baixar código
        uses: actions/checkout@v4
      
      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: 📦 Instalar dependências
        run: pip install -r requirements.txt
      
      - name: 🚀 Executar bot
        run:  python bot_shopee_telegram.py --now
        env:
          SHOPEE_APP_ID: ${{ secrets.SHOPEE_APP_ID }}
          SHOPEE_SECRET: ${{ secrets.SHOPEE_SECRET }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
